---
    - name: create the management server vms
      with_items:
        - "{{ management_vms }}"
      vmware_guest:
        validate_certs: False
        hostname: "{{ vmware_vcenter }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        cluster: "VDC-LABLON09"
        domain: "{{ domain }}"
        #name: "{{ cpman1_name }}"
        name: "{{ item.name }}"
        state: poweredon
        #folder: "{{ folder }}"
        #template: "{{ cpman1_template }}"
        template: "{{ item.template }}"
        datacenter: "{{ datacenter }}"
        customize: True
        dns_servers: "{{ dns_servers }}"
        ips: "{{ item.ip1 }}"
        networks: 
            #"{{ mgmt_network_address }}/25":
            "10.220.122.0/25": 
                network: "{{ mgmt_network_name }}"
                gateway: "{{ mgmt_network_gateway }}"
        #wait_for_ip_address: True
