---

# These variables are used by the vmware module to deploy vms. It doesn't work when defined as group_vars
mgmt_network: "10.220.{{mgmt_octet}}.0/25"
mgmt_network_address: "{{ mgmt_network | ipaddr }}"
mgmt_network_name:  "ll{{ lab_number }}-management"
mgmt_network_gateway: "10.220.{{mgmt_octet}}.126"

lab_networks:
    mgmt_network: 
        network_address: "{{ mgmt_network_address | ipaddr }}"
        network: "{{ mgmt_network_name }}"
        gateway: "{{ mgmt_network_gateway }}"
    
management_vms:
    - role: cpman1
      name: "{{ name_base }}-cpman1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.111"
      customize: True
    - role: cpman2
      name: "{{ name_base }}-cpman2"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.113"
      customize: True
    - role: dns1
      name: "{{ name_base }}-dns1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.107"
      customize: True
    - role: cpdb1
      name: "{{ name_base }}-cpdb1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.112"
      customize: True
    - role: cpvsp1
      name: "{{ name_short }}-cpvsp1"
      template: "vdc-lablon{{lab_number}}-cpvsp1-tpl"
      ip1: "10.220.{{mgmt_octet}}.116"
      customize: False

nameips:
    "cpman1": "10.220.{{mgmt_octet}}.111"
    "cpman2": "10.220.{{mgmt_octet}}.113"
    "dns1": "10.220.{{mgmt_octet}}.107"
    "dns2": "10.220.{{mgmt_octet}}.108"
    "cpdb1": "10.220.{{mgmt_octet}}.112"
    "cpvsp1": "10.220.{{mgmt_octet}}.116"
