---
vmware_vcenter: "VDC-LABLON09-VM.vdclab.internal"
vcenter_user: "gilil50"
vcenter_password: "Interoute01"

ip_octet: "{{ ip_range.split('.')[2] }}"
nfs_octet: "{{ ip_octet | int + 2 }}"
mgmt_octet: "{{ ip_octet | int + 2 }}"
iscsi_octet: "{{ ip_octet | int + 4 }}"

mgmt_network:  "10.220.{{mgmt_octet}}.0/25"

folder: "LABLON-{{ lab_number }}"
datacenter: "VDC-LABLON09" 
mgmt_network_address: "10.220.{{mgmt_octet}}.0/25"
mgmt_network_name:  "ll{{ lab_number }}-management"
mgmt_network_gateway: "10.220.{{mgmt_octet}}.126"

name_base: vdc-lablon{{ lab_number }}
name_short: vdc-ll{{ lab_number }}

domain: "lablon16.cp.vdc"

management_vms:
    - role: cpman1
      name: "{{ name_base }}-cpman1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.111"
    - role: dns1
      name: "{{ name_base }}-dns1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.107"
    - role: cpdb1
      name: "{{ name_base }}-cpdb1"
      template: "Centos7Shapeblue5"
      ip1: "10.220.{{mgmt_octet}}.112"
    - role: cpvsp1
      name: "{{ name_short }}-cpvsp1"
      template: "vdc-lablon{{lab_number}}-cpvsp1-tpl"
      ip1: "10.220.{{mgmt_octet}}.116"

cpman1_name: "vdc-test{{ lab_number }}_cpman1"
cpman1_template: 'Centos7ShapeBlue5'
cpman1_ip1: "10.220.{{mgmt_octet}}.111"

#cpman_template_name: "Centos7-Shapeblue5"
#ip1: '10.220.122.99'
