---
-   hosts: lablon16-dns
    pre_tasks:
       - setup:
            filter: ansible_*
    vars_files:
       -  vars/lab16.yml
    roles:
      - { role: installacs } 

-   hosts: 
       - lablon16-db
       - lablon16-cpman
    vars_files:
       -  vars/lab16.yml
    roles:
       - { role: installacs } 
