---
kickstart_file: "{{hw_eth0.macaddress_dash}}.{{inventory_hostname}}.ks"

ip_octet: "{{ ip_range.split('.')[2] }}"
esxi_octet: "{{ ip_octet | int}}"
esx_octet: "{{ ip_octet | int}}"
nfs_octet: "{{ ip_octet | int + 2 }}"
mgmt_octet: "{{ ip_octet | int + 2 }}"
iscsi_octet: "{{ ip_octet | int + 4 }}"

esx_vlan: "{{lab_number| int*100 + 11}}"
esxi_vlan: "{{lab_number| int*100 + 11}}"
nfs_vlan: "{{lab_number| int*100 + 7}}"
storage_vlan: "{{lab_number| int*100 + 7}}"
mgmt_vlan: "{{lab_number| int*100 + 2}}"
iscsi_vlan: "{{lab_number| int*100 + 4}}"

    
dns_servers:
    - "10.220.{{mgmt_octet}}.107"
    - "10.220.58.101"

tftp_path: "/var/lib/tftpboot"
html_path: "/var/www/html"
ks_server: "vdc-lablon10-ks1"

vmware_dvs:
    storage:
        name: storage
        mtu: 9000
        uplink_quantity: 2
        numPorts: 128
        discovery_protocol: "cdp"
        discovery_operation: "both"
        portgroups:
            - name: "VMk-NFS"
              port_binding: "dynamic"
              portgroup_type: "earlyBinding"
              port_allocation: "elastic"
              numPorts: 64
              vlan: "{{lab_number}}07"
              mtu: 9000
              vmkipdiff: 2
              subnet_mask: "255.255.255.128" 
            - name: "VMk-iSCSI-1"
              port_binding: "dynamic"
              portgroup_type: "earlyBinding"
              port_allocation: "elastic"
              numPorts: 64
              vlan: "{{lab_number}}04"
            - name: "VMk-iSCSI-2"
              port_binding: "dynamic"
              portgroup_type: "earlyBinding"
              port_allocation: "elastic"
              numPorts: 64
              vlan: "{{lab_number}}04"
            - name: "VMk-vMotion"
              port_binding: "dynamic"
              portgroup_type: "earlyBinding"
              port_allocation: "elastic"
              numPorts: 64
              vlan: "{{lab_number}}07"
    external:
        name: external
        mtu: 9000
        uplink_quantity: 2
        numPorts: 128
        discovery_protocol: "cdp"
        discovery_operation: "both"
        portgroups:
           - name: 'Management Network'
             port_binding: "dynamic"
             portgroup_type: "earlyBinding"
             port_allocation: "elastic"
             numPorts: 64
             vlan: "{{lab_number}}11"

esxi_username: "root"
esxi_password: "Interoute01"

