---
    - include: cpman_pre.yml

    - name: Cloudstack Setup Databases cpman2
      command: "/usr/bin/cloudstack-setup-databases cloud:{{password}}@{{db_server}} -e file -m {{password}} -k {{password}} -i {{ansible_hostname}}"
      when: '"cpman2" in ansible_hostname'
      tags:
        - initial_install

    - name: Cloudstack Setup Tomcat
      command: "/usr/bin/cloudstack-setup-management --tomcat7"
      tags:
        - initial_install
        - reinstall

    - name: Restart Cloudstack
      tags:
        - initial_install
        - reinstall
        - test
      systemd:
            name: "{{ item }}"
            state: restarted
      with_items:
            - "cloudstack-management"
            - "cloudstack-usage"

    - name: Ensure Firewalld and iptables ervice is stopped
      systemd:
        name:  "{{ item }}"
        state: stopped
        enabled: False
      with_items:
        - iptables
        - firewalld
      tags:
        - initial_install
        - reinstall
